// Generated by characters/charactergen.py from characters/pixel/character.json. Do not edit.
// The character's moods in its pack's order (characters/CHARACTER.md §9).
#pragma once
#include <cstdint>

namespace render {

enum class Mood : uint8_t {
  kHappy,
  kExcited,
  kProud,
  kCurious,
  kDetermined,
  kGrumpy,
  kSad,
  kCalm,
  kEngaged,
  kAnnoyed,
  kIrritated,
  kWhiny,
  kWounded,
  kCount
};
constexpr int kMoodCount = 13;
// What the board shows before the Mac sends a mood, and for a name it
// doesn't know: the pack's startup_mood, else its default_mood.
constexpr Mood kStartupMood = Mood::kHappy;
constexpr const char* kMoodNames[kMoodCount] = {"happy", "excited", "proud", "curious", "determined", "grumpy", "sad", "calm", "engaged", "annoyed", "irritated", "whiny", "wounded"};

}  // namespace render
